var kissers = [
    {   "name" : "besador básico",
        "cost" : 20,
        "dps" : 1,
        "totalDps" : 0,
        "cuantity": 0,
        "alreadyShown" : 0,
        "description" : ""
    },
    {   "name" : "besador no tan básico",
        "cost" : 100,
        "dps" : 5,
        "totalDps" : 0,
        "cuantity": 0,
        "alreadyShown" : 0,
        "description" : ""
    },
    {   "name" : "besador algo mejor",
        "cost" : 500,
        "dps" : 25,
        "totalDps" : 0,
        "cuantity": 0,
        "alreadyShown" : 0,
        "description" : ""
    },
    {   "name" : "besador casi aceptable",
        "cost" : 2000,
        "dps" : 125,
        "totalDps" : 0,
        "cuantity": 0,
        "alreadyShown" : 0,
        "description" : ""
    },
    {   "name" : "besador decente",
        "cost" : 8000,
        "dps" : 625,
        "totalDps" : 0,
        "cuantity": 0,
        "alreadyShown" : 0,
        "description" : ""
    },
    {   "name" : "besador bueno",
        "cost" : 32000,
        "dps" : 3125,
        "totalDps" : 0,
        "cuantity": 0,
        "alreadyShown" : 0,
        "description" : ""
    },
    {   "name" : "besador lindo",
        "cost" : 96000,
        "dps" : 15625,
        "totalDps" : 0,
        "cuantity": 0,
        "alreadyShown" : 0,
        "description" : ""
    },
    {   "name" : "besador besucón",
        "cost" : 300000,
        "dps" : 78125,
        "totalDps" : 0,
        "cuantity": 0,
        "alreadyShown" : 0,
        "description" : ""
    },
    {   "name" : "besador bello",
        "cost" : 900000,
        "dps" : 390625,
        "totalDps" : 0,
        "cuantity": 0,
        "alreadyShown" : 0,
        "description" : ""
    },
    {   "name" : "Súper besador",
        "cost" : 3000000,
        "dps" : 1953125,
        "totalDps" : 0,
        "cuantity": 0,
        "alreadyShown" : 0,
        "description" : ""
    }
]