    var initialKissers = [
    {   "name" : "Besador básico",
        "cost" : 20,
        "dps" : 1,
        "totalDps" : 0,
        "cuantity": 0,
        "alreadyShown" : 0,
        "description" : "",
    },
    {   "name" : "Besador no tan básico",
        "cost" : 200,
        "dps" : 10,
        "totalDps" : 0,
        "cuantity": 0,
        "alreadyShown" : 0,
        "description" : ""
    },
    {   "name" : "Besador algo mejor",
        "cost" : 2000,
        "dps" : 100,
        "totalDps" : 0,
        "cuantity": 0,
        "alreadyShown" : 0,
        "description" : ""
    },
    {   "name" : "Besador casi aceptable",
        "cost" : 20000,
        "dps" : 1000,
        "totalDps" : 0,
        "cuantity": 0,
        "alreadyShown" : 0,
        "description" : ""
    },
    {   "name" : "Besador decente",
        "cost" : 200000,
        "dps" : 10000,
        "totalDps" : 0,
        "cuantity": 0,
        "alreadyShown" : 0,
        "description" : ""
    },
    {   "name" : "Besador bueno",
        "cost" : 2000000,
        "dps" : 100000,
        "totalDps" : 0,
        "cuantity": 0,
        "alreadyShown" : 0,
        "description" : ""
    },
    {   "name" : "Besador lindo",
        "cost" : 20000000,
        "dps" : 1000000,
        "totalDps" : 0,
        "cuantity": 0,
        "alreadyShown" : 0,
        "description" : ""
    },
    {   "name" : "Besador besucón",
        "cost" : 200000000,
        "dps" : 10000000,
        "totalDps" : 0,
        "cuantity": 0,
        "alreadyShown" : 0,
        "description" : ""
    },
    {   "name" : "Besador bello",
        "cost" : 2000000000,
        "dps" : 100000000,
        "totalDps" : 0,
        "cuantity": 0,
        "alreadyShown" : 0,
        "description" : ""
    },
    {   "name" : "Súper besador",
        "cost" : 20000000000,
        "dps" : 1000000000,
        "totalDps" : 0,
        "cuantity": 0,
        "alreadyShown" : 0,
        "description" : ""
    }
]